name: Installing Python

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        py-version: [3.12, 3.13, 3.11]
        os: [ubuntu-22.04, macos-13, windows-2022]
        exclude:
          - os: macos-13
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py-version}}
