name: Installing Python

on: [push]

jobs:
  build:
    strategy:
      matrix:
        py-version: [3.14, 3.13, .3.12]
        os: [ubuntu-22.04, macos-14, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py-version}}
